// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1sTMkeyHaLr5jpdk00wOBCeLny4FozuM',
    appId: '1:429052372556:web:f9b110ad0422818bd176e9',
    messagingSenderId: '429052372556',
    projectId: 'calendz-app',
    authDomain: 'calendz-app.firebaseapp.com',
    storageBucket: 'calendz-app.appspot.com',
    measurementId: 'G-1H9NHFPK7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDHLQoVKUSP2ZImFirh5laYT1J62QXfU',
    appId: '1:429052372556:android:cdec9c8ca6cf6439d176e9',
    messagingSenderId: '429052372556',
    projectId: 'calendz-app',
    storageBucket: 'calendz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrOi9LcuKkElew_r3f3tmTjtzsb9SXkA',
    appId: '1:429052372556:ios:ac325c883669af9ed176e9',
    messagingSenderId: '429052372556',
    projectId: 'calendz-app',
    storageBucket: 'calendz-app.appspot.com',
    iosClientId: '429052372556-3ov4i0aap05rio8uc2b2vtjj78mkspnu.apps.googleusercontent.com',
    iosBundleId: 'com.calendz.app',
  );
}
